name: Release

on:
  push:
    branches: [release/*]

jobs:
  create-perl-release:
    name: Publish to CPAN
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cucumber/action-publish-cpan@v1.0.0
        with:
          cpan-user: ${{ secrets.CPAN_USER }}
          cpan-password: ${{ secrets.CPAN_PASSWORD }}
          working-directory: 'perl'

  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cucumber/action-create-github-release@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-go-subrepo:
    name: Publish to cucumber/messgaes-go subrepo
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: cucumber/action-publish-subrepo@v1.1.0
        with:
          working-directory: go
          github-token: ${{ secrets.CUKEBOT_GITHUB_TOKEN }}

  create-hex-release:
    name: Publish to hex.pm
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.10.x'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: cucumber/action-publish-hex@v1.0.0
        with:
          hex-api-key: ${{ secrets.HEX_API_KEY }}
          working-directory: 'elixir'

  publish-mvn:
    name: Publish Maven Package
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - uses: cucumber/action-publish-mvn@v2.0.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: cukebot
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
          working-directory: java

  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: javascript/package-lock.json
      - run: npm install-test
        working-directory: javascript
      - uses: cucumber/action-publish-npm@v1.1.0
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          working-directory: javascript

  publish-nuget:
    name: Publish package to NuGet.org
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: cucumber/action-publish-nuget@v1.0.0
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          working-directory: "dotnet"

  create-php-release:
    name: Publish to PHP subrepo
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: cucumber/action-publish-subrepo@v1.1.0
        with:
          working-directory: php
          github-token: ${{ secrets.CUKEBOT_GITHUB_TOKEN }}

  publish-rubygem:
    name: Publish Ruby Gem
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true
      - uses: cucumber/action-publish-rubygem@v1.0.0
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          working_directory: ruby
